# --- 1. On utilise TON image prébuildée ---
FROM ghcr.io/jichiory/translater:latest

# Variables d'environnement
ENV SOURCE_LANG=fr
ENV TARGET_LANG=en
ENV INPUT_DIR=/app/input
ENV OUTPUT_DIR=/app/output
# --- 2. On copie ton code Python "léger" ---
WORKDIR /app
COPY src/main.py .
COPY input/ ./input/

# --- 3. On définit la commande par défaut ---
CMD ["python", "main.py"]
